### ISSUE TITLE
Django2.1集成simditor报错

### ISSUE THREAD

**Issue by Dumbliidore** [istommao/django-simditor#12]
TypeError at /admin/blog/post/add/
render() got an unexpected keyword argument 'renderer'

**Comment by istommao** [comment]
@BlueMrD 错误信息太少了，你得给个详细的错误context

**Comment by Dumbliidore** [comment]
@istommao 
你可以看看这里，我发现很多编辑器在对Django最新版本的支持上都有类似的问题。
[ckeditor](https://github.com/django-ckeditor/django-ckeditor/issues/503)

**Comment by istommao** [comment]
@BlueMrD 0.0.11版本已修复

**Comment by Dumbliidore** [comment]
更新后可正常使用，十分感谢。加入 {% csrf_token %} 好评。
