### ISSUE TITLE
Nginx部署上线之后，与imagefiled好像冲突，图片上传失败

### ISSUE THREAD

**Issue by downdawn** [istommao/django-simditor#13]
类里面：
 class Post(models.Model):

    title = models.CharField(max_length=70,verbose_name='文章')
    image = models.ImageField(upload_to='uploads', verbose_name='图片')
    body = RichTextField(verbose_name='正文')

setting里面：
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

SIMDITOR_UPLOAD_PATH = 'uploads/'
SIMDITOR_IMAGE_BACKEND = 'pillow'

Nginx事件里面：
 location /static { 
        alias /home/ubuntu/sites/downdawn.com/myblog2/static; 
    }
    location /media {
        alias /home/ubuntu/sites/downdawn.com/myblog2/media;

**Comment by istommao** [comment]
图片上传和nginx这个配置没关系，你看看 django哪里配置不正确
图片上传失败是如何提示的？请求信息看看

**Comment by downdawn** [comment]
已经找到原因了。谢谢你。请教你一个问题：我想要获取RichTextField中的内容要如何操作？

**Comment by istommao** [comment]
这个你在view里面试下吧 @downdawn
