### ISSUE TITLE
图片压缩怎么设置？还有设置上传图片大小。

### ISSUE THREAD

**Issue by yuzg667** [istommao/django-simditor#16]

**Comment by istommao** [comment]
目前还没有这个功能，后期可以加上

**Comment by yuzg667** [comment]
当前有没有其他方法控制上传图片的？

**Comment by istommao** [comment]
```python
SIMDITOR_CONFIGS = {
    'toolbar': SIMDITOR_TOOLBAR,
    'upload': {
        'url': '/simditor/upload/',
        'fileKey': 'upload',
        'image_size': 1024 * 1024 * 4   # max image size 4MB
    },
    'emoji': {
        'imagePath': '/static/simditor/images/emoji/'
    }
}
```

大小限制加了  image_size @yuzg667

**Comment by yuzg667** [comment]
> ```python
> SIMDITOR_CONFIGS = {
>     'toolbar': SIMDITOR_TOOLBAR,
>     'upload': {
>         'url': '/simditor/upload/',
>         'fileKey': 'upload',
>         'image_size': 1024 * 1024 * 4   # max image size 4MB
>     },
>     'emoji': {
>         'imagePath': '/static/simditor/images/emoji/'
>     }
> }
> ```
> 
> 大小限制加了 image_size @yuzg667

最新代码亲测有效，谢谢！该问题已解决
