### ISSUE TITLE
在xmaind中使用出现错误

### ISSUE THREAD

**Issue by downdawn** [istommao/django-simditor#18]
我在xmaind中跑起来之后，编辑的内容全部变成[HTML_REMOVED]。。。

**Comment by istommao** [comment]
你说 xadmin吗？能发下截图等信息吗 @downdawn

**Comment by downdawn** [comment]
![image](https://user-images.githubusercontent.com/41266749/48540684-bd939f00-e8f5-11e8-89c0-ad44ce451a6d.png)
![image](https://user-images.githubusercontent.com/41266749/48540710-cc7a5180-e8f5-11e8-87d1-eab37d2048fa.png)
h
![image](https://user-images.githubusercontent.com/41266749/48541074-c5077800-e8f6-11e8-9361-633edd995745.png)
好像是被custom_markdown占用了，导致不能加载失败

**Comment by istommao** [comment]
现在ok了是吗 @downdawn

**Comment by downdawn** [comment]
还是不行的，重写了方法会被覆盖掉，起冲突

**Comment by istommao** [comment]
@downdawn 看你后台可以显示出来的话应该  和 django-simditor 没关系了
你这个是 前台模版渲染，应该和 custom_markdown 和 safe 有关系
