### ISSUE TITLE
在Django admin外，怎么使用

### ISSUE THREAD

**Issue by gotoing** [istommao/django-simditor#3]
我想在 Django的 前端使用，比如评论这些，请问咋个使用

**Comment by istommao** [comment]
目前是集成到 django admin的，你需要想要使用的话 可以直接 使用 simditor http://simditor.tower.im/
以后看看加上这个功能

**Comment by istommao** [comment]
@gotoing 示例已添加，具体可以看simditor_demo
https://github.com/istommao/django-simditor#without-django-admin-demo

**Comment by w2n1ck** [comment]
怎么配置使用呢？说明文档详细说下呗

**Comment by istommao** [comment]
@w2n1ck  readme中有说明 https://github.com/istommao/django-simditor#without-django-admin-demo
simditor_demo中你可以clone下来代码跑起来也有示例
