### ISSUE TITLE
下拉页面的时候，向上浮动，

### ISSUE THREAD

**Issue by zhaojj11** [istommao/django-simditor#4]
您好！我在使用时，遇到了这样的问题请问该如何解决呢
![image](https://user-images.githubusercontent.com/26586269/36469025-c2530d16-1720-11e8-9553-af6f823b1e59.png)
一下拉就会变成这样
![image](https://user-images.githubusercontent.com/26586269/36469013-b704deee-1720-11e8-8bcd-7af033e43e46.png) 

怎么去除浮动效果呢，我在setting里写了也没什么用

**Comment by istommao** [comment]
这个是个bug，后期我会修复

**Comment by zhaojj11** [comment]
万分感谢！

**Comment by istommao** [comment]
已在 0.0.9版本修复, 注意清空浏览器缓存

**Comment by zhaojj11** [comment]
谢谢！
