### ISSUE TITLE
感觉对移动端不是很友好

### ISSUE THREAD

**Issue by zhaojj11** [istommao/django-simditor#5]
之前的小bug还是有

**Comment by istommao** [comment]
这个不支持移动端，bug你更新到 0.0.10版本看看

**Comment by zhaojj11** [comment]
您好，请问，代码块高亮怎么设置

**Comment by istommao** [comment]
编辑器里面显示是没有高亮的，如果是渲染的页面需要自己根据需要加上相关的高亮js

**Comment by zhaojj11** [comment]
感谢，不过关于字体文件报了404的错误，这该怎么解决呢

**Comment by istommao** [comment]
截图看看？

**Comment by zhaojj11** [comment]
只是两个会出现的问题
![image](https://user-images.githubusercontent.com/26586269/36705130-8f727e86-1b9e-11e8-8afc-64afabfc42bf.png)
![image](https://user-images.githubusercontent.com/26586269/36705213-e9803120-1b9e-11e8-8da8-751036c10c84.png)


js文件是没问题的
![image](https://user-images.githubusercontent.com/26586269/36705148-a6919cc8-1b9e-11e8-9be8-acd1a5f6b92f.png)
![image](https://user-images.githubusercontent.com/26586269/36705170-c2b34082-1b9e-11e8-9f51-c16c22ebab43.png)

**Comment by istommao** [comment]
你用nginx的吧？有做 ./manage.py collectstatic 吗
然后 settings.py 里面要设置下
![image](https://user-images.githubusercontent.com/5070879/36705258-27f47b8c-1b9f-11e8-865c-88d4c6ac4fc5.png)

**Comment by zhaojj11** [comment]
是的 我都这也么做了

![image](https://user-images.githubusercontent.com/26586269/36705310-6682180a-1b9f-11e8-9945-6c2a6307e011.png)

而且https://pyjava.com/static/simditor/scripts/hotkeys.js 这个能访问哎

**Comment by istommao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
你nginx怎么配的看下？                



    在2018年02月27日 09:22，myblog<notifications@github.com> 写道： 


是的 我都这也么做了

而且https://pyjava.com/static/simditor/scripts/hotkeys.js 这个能访问哎

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  





        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }

**Comment by zhaojj11** [comment]
sorry ,我刚才把一段注释掉add_header 注释掉就可以了
感谢！！
https://github.com/sandorZHAO/website/blob/master/nginx.conf
